import { describe, it, expect } from 'vitest'

/**
 * Export Integrity Tests
 *
 * These tests verify that every component, hook, utility, and type
 * is correctly exported from the main barrel file. This prevents
 * regressions where a component exists but isn't properly exported.
 */

describe('Main Barrel Exports (@premiumui/core)', () => {
  it('exports all utility functions', async () => {
    const mod = await import('../index')
    expect(mod.cn).toBeTypeOf('function')
    expect(mod.formatNumber).toBeTypeOf('function')
    expect(mod.formatCurrency).toBeTypeOf('function')
    expect(mod.formatPercent).toBeTypeOf('function')
    expect(mod.uniqueId).toBeTypeOf('function')
  })

  it('exports all hooks', async () => {
    const mod = await import('../index')
    expect(mod.useTheme).toBeTypeOf('function')
    expect(mod.useReducedMotion).toBeTypeOf('function')
    expect(mod.useAnimatedNumber).toBeTypeOf('function')
  })

  it('exports all animation presets', async () => {
    const mod = await import('../index')
    expect(mod.springSnappy).toBeDefined()
    expect(mod.springGentle).toBeDefined()
    expect(mod.springBouncy).toBeDefined()
    expect(mod.springHeavy).toBeDefined()
    expect(mod.fadeVariants).toBeDefined()
    expect(mod.fadeUpVariants).toBeDefined()
    expect(mod.fadeDownVariants).toBeDefined()
    expect(mod.scaleInVariants).toBeDefined()
    expect(mod.scaleInBounceVariants).toBeDefined()
    expect(mod.slideRightVariants).toBeDefined()
    expect(mod.slideLeftVariants).toBeDefined()
    expect(mod.slideUpVariants).toBeDefined()
    expect(mod.staggerContainerVariants).toBeDefined()
    expect(mod.staggerFastVariants).toBeDefined()
    expect(mod.hoverLiftProps).toBeDefined()
    expect(mod.hoverPressProps).toBeDefined()
    expect(mod.backdropVariants).toBeDefined()
    expect(mod.modalVariants).toBeDefined()
    expect(mod.reducedMotionVariants).toBeDefined()
    expect(mod.createStaggerVariants).toBeTypeOf('function')
  })

  it('exports theme system', async () => {
    const mod = await import('../index')
    expect(mod.themes).toBeDefined()
    expect(mod.themeNames).toBeDefined()
    expect(mod.themeFamilies).toBeDefined()
  })

  it('exports all dashboard components', async () => {
    const mod = await import('../index')
    expect(mod.KpiStatCard).toBeDefined()
    expect(mod.KpiGrid).toBeDefined()
    expect(mod.RevenueChart).toBeDefined()
    expect(mod.BarChartBlock).toBeDefined()
    expect(mod.DonutChartBlock).toBeDefined()
    expect(mod.ActivityFeed).toBeDefined()
    expect(mod.MiniSparklineRow).toBeDefined()
    expect(mod.MetricComparisonCard).toBeDefined()
    expect(mod.GoalProgressCard).toBeDefined()
    expect(mod.HeatmapCalendar).toBeDefined()
    expect(mod.RealTimeCounter).toBeDefined()
    expect(mod.DashboardShell).toBeDefined()
  })

  it('exports all data table components', async () => {
    const mod = await import('../index')
    expect(mod.DataTable).toBeDefined()
    expect(mod.ExpandableRowTable).toBeDefined()
    expect(mod.EditableTable).toBeDefined()
    expect(mod.CardListView).toBeDefined()
    expect(mod.SortableList).toBeDefined()
    expect(mod.VirtualList).toBeDefined()
    expect(mod.KanbanBoard).toBeDefined()
    expect(mod.TimelineList).toBeDefined()
    expect(mod.NestedTreeList).toBeDefined()
    expect(mod.CommandPaletteList).toBeDefined()
  })

  it('exports all form components', async () => {
    const mod = await import('../index')
    expect(mod.LoginForm).toBeDefined()
    expect(mod.RegistrationForm).toBeDefined()
    expect(mod.MultiStepForm).toBeDefined()
    expect(mod.SettingsForm).toBeDefined()
    expect(mod.SearchInput).toBeDefined()
    expect(mod.DateRangePicker).toBeDefined()
    expect(mod.FileUploadZone).toBeDefined()
    expect(mod.PaymentForm).toBeDefined()
    expect(mod.AddressForm).toBeDefined()
    expect(mod.InlineEditField).toBeDefined()
    expect(mod.TagMultiSelect).toBeDefined()
    expect(mod.OtpInput).toBeDefined()
  })

  it('exports all navigation components', async () => {
    const mod = await import('../index')
    expect(mod.CollapsibleSidebar).toBeDefined()
    expect(mod.TopNavBar).toBeDefined()
    expect(mod.BreadcrumbTrail).toBeDefined()
    expect(mod.TabNavigation).toBeDefined()
    expect(mod.CommandPalette).toBeDefined()
    expect(mod.MobileBottomNav).toBeDefined()
    expect(mod.MegaMenu).toBeDefined()
    expect(mod.PageTransition).toBeDefined()
    expect(mod.FloatingActionMenu).toBeDefined()
    expect(mod.StepperNavigation).toBeDefined()
  })

  it('exports all feedback components', async () => {
    const mod = await import('../index')
    expect(mod.Toast).toBeDefined()
    expect(mod.ModalDialog).toBeDefined()
    expect(mod.SlideOverPanel).toBeDefined()
    expect(mod.ConfirmationDialog).toBeDefined()
    expect(mod.Tooltip).toBeDefined()
    expect(mod.Popover).toBeDefined()
    expect(mod.AlertBanner).toBeDefined()
    expect(mod.SkeletonLoader).toBeDefined()
    expect(mod.EmptyState).toBeDefined()
    expect(mod.ProgressIndicator).toBeDefined()
  })

  it('exports all card components', async () => {
    const mod = await import('../index')
    expect(mod.PricingCard).toBeDefined()
    expect(mod.PricingTable).toBeDefined()
    expect(mod.TestimonialCard).toBeDefined()
    expect(mod.FeatureCard).toBeDefined()
    expect(mod.BlogCard).toBeDefined()
    expect(mod.UserProfileCard).toBeDefined()
    expect(mod.ProductCard).toBeDefined()
    expect(mod.NotificationCard).toBeDefined()
    expect(mod.StatCard).toBeDefined()
    expect(mod.CtaBannerCard).toBeDefined()
  })

  it('exports all AI components', async () => {
    const mod = await import('../index')
    expect(mod.ChatInterface).toBeDefined()
    expect(mod.ChatBubble).toBeDefined()
    expect(mod.StreamingText).toBeDefined()
    expect(mod.PromptInputBar).toBeDefined()
    expect(mod.AIResponseCard).toBeDefined()
    expect(mod.RAGSourceCitation).toBeDefined()
    expect(mod.AgentStatusCard).toBeDefined()
    expect(mod.ModelSelector).toBeDefined()
    expect(mod.TokenUsageMeter).toBeDefined()
    expect(mod.KnowledgeBaseList).toBeDefined()
  })

  it('exports all e-commerce components', async () => {
    const mod = await import('../index')
    expect(mod.ShoppingCartDrawer).toBeDefined()
    expect(mod.ProductQuickView).toBeDefined()
    expect(mod.CheckoutSummary).toBeDefined()
    expect(mod.ProductImageGallery).toBeDefined()
    expect(mod.ReviewBlock).toBeDefined()
    expect(mod.CartItemRow).toBeDefined()
    expect(mod.WishlistGrid).toBeDefined()
    expect(mod.PromoCodeInput).toBeDefined()
  })

  it('exports all auth components', async () => {
    const mod = await import('../index')
    expect(mod.SocialAuthButtons).toBeDefined()
    expect(mod.TwoFactorAuth).toBeDefined()
    expect(mod.OnboardingWizard).toBeDefined()
    expect(mod.PasswordResetFlow).toBeDefined()
    expect(mod.TeamInviteForm).toBeDefined()
    expect(mod.ProfileSetupCard).toBeDefined()
  })

  it('exports all utility components', async () => {
    const mod = await import('../index')
    expect(mod.ThemeSwitcher).toBeDefined()
    expect(mod.KeyboardShortcutDisplay).toBeDefined()
    expect(mod.ChangelogModal).toBeDefined()
    expect(mod.CookieConsentBanner).toBeDefined()
    expect(mod.FeedbackWidget).toBeDefined()
    expect(mod.CopyButton).toBeDefined()
    expect(mod.AvatarGroup).toBeDefined()
    expect(mod.TagCollection).toBeDefined()
    expect(mod.AnnouncementBar).toBeDefined()
    expect(mod.ErrorPage).toBeDefined()
    expect(mod.MaintenancePage).toBeDefined()
    expect(mod.IntegrationsGrid).toBeDefined()
  })

  it('exports all developer tools components', async () => {
    const mod = await import('../index')
    expect(mod.ApiKeyManager).toBeDefined()
    expect(mod.WebhookTester).toBeDefined()
    expect(mod.EnvironmentVariableEditor).toBeDefined()
    expect(mod.LogViewer).toBeDefined()
    expect(mod.JsonInspector).toBeDefined()
    expect(mod.ApiPlayground).toBeDefined()
    expect(mod.DeploymentPipeline).toBeDefined()
    expect(mod.SchemaVisualizer).toBeDefined()
    expect(mod.CodeSnippetBlock).toBeDefined()
    expect(mod.FeatureFlagPanel).toBeDefined()
  })

  it('exports all SaaS platform components', async () => {
    const mod = await import('../index')
    expect(mod.SubscriptionManager).toBeDefined()
    expect(mod.UsageBillingDashboard).toBeDefined()
    expect(mod.TeamManagementPanel).toBeDefined()
    expect(mod.AuditLogViewer).toBeDefined()
    expect(mod.PermissionsMatrix).toBeDefined()
    expect(mod.OnboardingChecklist).toBeDefined()
    expect(mod.TenantSwitcher).toBeDefined()
    expect(mod.QuotaUsageCard).toBeDefined()
    expect(mod.CustomerHealthScore).toBeDefined()
    expect(mod.ChangelogTimeline).toBeDefined()
  })

  it('exports all AI ops components', async () => {
    const mod = await import('../index')
    expect(mod.LlmPlayground).toBeDefined()
    expect(mod.PromptTemplateEditor).toBeDefined()
    expect(mod.EvaluationResultsTable).toBeDefined()
    expect(mod.VectorSearchExplorer).toBeDefined()
    expect(mod.AgentWorkflowBuilder).toBeDefined()
    expect(mod.ModelComparisonCard).toBeDefined()
    expect(mod.CostTrackerDashboard).toBeDefined()
    expect(mod.AnnotationLabelingTool).toBeDefined()
    expect(mod.GuardrailConfigPanel).toBeDefined()
    expect(mod.DatasetBrowser).toBeDefined()
  })

  it('exports all internal tools components', async () => {
    const mod = await import('../index')
    expect(mod.CrudResourcePanel).toBeDefined()
    expect(mod.ApprovalWorkflow).toBeDefined()
    expect(mod.BulkActionToolbar).toBeDefined()
    expect(mod.ReportBuilder).toBeDefined()
    expect(mod.NotificationCenter).toBeDefined()
    expect(mod.SystemStatusDashboard).toBeDefined()
    expect(mod.ImportExportWizard).toBeDefined()
    expect(mod.RoleBasedNavShell).toBeDefined()
    expect(mod.TaskQueueMonitor).toBeDefined()
    expect(mod.ConfigurationPanel).toBeDefined()
  })

  it('exports all CLI & web terminal components', async () => {
    const mod = await import('../index')
    expect(mod.TerminalEmulator).toBeDefined()
    expect(mod.CliOutputRenderer).toBeDefined()
    expect(mod.McpServerStatus).toBeDefined()
    expect(mod.AgentChatTerminal).toBeDefined()
    expect(mod.PipelineLogStream).toBeDefined()
    expect(mod.CommandBuilderForm).toBeDefined()
    expect(mod.DiffViewer).toBeDefined()
    expect(mod.SshConnectionManager).toBeDefined()
    expect(mod.CronScheduleEditor).toBeDefined()
    expect(mod.WebhookEventLog).toBeDefined()
  })

  it('exports all collaboration components', async () => {
    const mod = await import('../index')
    expect(mod.CommentThread).toBeDefined()
    expect(mod.MentionInput).toBeDefined()
    expect(mod.PresenceIndicator).toBeDefined()
    expect(mod.SharedCursor).toBeDefined()
    expect(mod.ReactionPicker).toBeDefined()
    expect(mod.ActivityTimeline).toBeDefined()
    expect(mod.InviteLinkCard).toBeDefined()
    expect(mod.VotingPoll).toBeDefined()
    expect(mod.LiveBadge).toBeDefined()
    expect(mod.CollaborativeEditorToolbar).toBeDefined()
  })

  it('exports all media components', async () => {
    const mod = await import('../index')
    expect(mod.ImageCropper).toBeDefined()
    expect(mod.VideoPlayer).toBeDefined()
    expect(mod.AudioWaveform).toBeDefined()
    expect(mod.FileBrowser).toBeDefined()
    expect(mod.DocumentViewer).toBeDefined()
    expect(mod.MediaGrid).toBeDefined()
    expect(mod.UploadProgressCard).toBeDefined()
    expect(mod.CloudStorageMeter).toBeDefined()
    expect(mod.AttachmentChip).toBeDefined()
    expect(mod.ScreenRecordingCard).toBeDefined()
  })

  it('exports all scheduling components', async () => {
    const mod = await import('../index')
    expect(mod.MonthCalendar).toBeDefined()
    expect(mod.WeekPlanner).toBeDefined()
    expect(mod.EventCard).toBeDefined()
    expect(mod.AvailabilityPicker).toBeDefined()
    expect(mod.TimezoneSelector).toBeDefined()
    expect(mod.CountdownTimer).toBeDefined()
    expect(mod.BookingConfirmation).toBeDefined()
    expect(mod.RecurringScheduleEditor).toBeDefined()
    expect(mod.GanttRow).toBeDefined()
    expect(mod.AgendaList).toBeDefined()
  })

  it('exports all maps components', async () => {
    const mod = await import('../index')
    expect(mod.LocationPicker).toBeDefined()
    expect(mod.AddressAutocomplete).toBeDefined()
    expect(mod.StoreLocatorCard).toBeDefined()
    expect(mod.RouteSummary).toBeDefined()
    expect(mod.GeofenceEditor).toBeDefined()
    expect(mod.DeliveryTracker).toBeDefined()
    expect(mod.HeatmapOverlay).toBeDefined()
    expect(mod.CoordinatesDisplay).toBeDefined()
    expect(mod.RegionSelector).toBeDefined()
    expect(mod.EtaCard).toBeDefined()
  })

  it('exports all messaging components', async () => {
    const mod = await import('../index')
    expect(mod.InboxPanel).toBeDefined()
    expect(mod.PushNotificationCard).toBeDefined()
    expect(mod.EmailComposer).toBeDefined()
    expect(mod.SmsPreview).toBeDefined()
    expect(mod.NotificationPreferences).toBeDefined()
    expect(mod.MessageStatusRow).toBeDefined()
    expect(mod.BroadcastComposer).toBeDefined()
    expect(mod.UnreadBadgeStack).toBeDefined()
    expect(mod.DigestSummaryCard).toBeDefined()
    expect(mod.WebhookNotificationCard).toBeDefined()
  })

  it('total exports count is at least 200 components', async () => {
    const mod = await import('../index')
    const exportedNames = Object.keys(mod).filter(
      (key) => typeof mod[key as keyof typeof mod] === 'function' || typeof mod[key as keyof typeof mod] === 'object',
    )
    // 200+ components + utilities + hooks + animations + themes
    expect(exportedNames.length).toBeGreaterThanOrEqual(200)
  })
})
